# spring config
spring:
  application.name: memory-game-backend
  datasource:
    url: jdbc:h2:mem:memorygamedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
      show_sql: true
      hbm2ddl:
        auto: create-drop
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

# app info
info:
  app:
    name: @project.name@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@

#server configuration(This port configuration is HTTPS)
server:
  port: 8081
  servlet:
    context-path: /memorygame

## Log settings
logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.rodrigovsilva: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/memory-game.log
  file.max-history: 10
  file.max-size: 50MB

#actuator configurations
management:
  endpoint:
    actuator:
      enabled: true
    health:
      enabled: true
    enabled-by-default: true





